version: "2.4"

services:

  dev:
    build: .
    volumes:
      - .:/project
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: cfdb
      MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - 3306:3306